### ISSUE TITLE
On a fresh install, running npm run package yields errors

### ISSUE THREAD

**Issue by ggoforth** [cameronhunter/generator-alexa-skill#27]
Just started working with this a few days ago, and it's been awesome.  Had no issues at first, but now, running `npm run package` per the readme, on a brand new fresh install is yielding some errors for me.

The first is:

```
ERROR in ./src/skill.js
Module build failed: TypeError: /Users/greg/projects/alexa-skills/chess/skill/src/skill.js: Duplicate declaration "Skill"
  4 |
  5 | @Skill
  6 | export default class Skill {
    |                      ^
```

The second is:

```
Error: Cannot find module "./skill"
    at /Users/greg/projects/alexa-skills/chess/skill/build/webpack:/src/index.js:1:1
    at Object.exports.handler.t.(anonymous function).Object.(anonymous function).writable (/Users/greg/projects/alexa-skills/chess/skill/build/webpack:/src/index.js:1:1)
    at n (/Users/greg/projects/alexa-skills/chess/skill/build/webpack:/webpack/bootstrap 34284e9e990cdad94ba8:19:1)
    at Object.<anonymous> (/Users/greg/projects/alexa-skills/chess/skill/build/webpack:/index.js:49:19)
    at n (/Users/greg/projects/alexa-skills/chess/skill/build/webpack:/webpack/bootstrap 34284e9e990cdad94ba8:19:1)
    at /Users/greg/projects/alexa-skills/chess/skill/build/webpack:/webpack/bootstrap 34284e9e990cdad94ba8:39:1
    at Object.<anonymous> (/Users/greg/projects/alexa-skills/chess/skill/build/webpack:/webpack/bootstrap 34284e9e990cdad94ba8:39:1)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at extensions.(anonymous function) (/Users/greg/projects/alexa-skills/chess/skill/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/greg/projects/alexa-skills/chess/skill/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/greg/projects/alexa-skills/chess/skill/test/index-test.js:2:1)
    at Module._compile (module.js:413:34)
    at extensions.(anonymous function) (/Users/greg/projects/alexa-skills/chess/skill/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/greg/projects/alexa-skills/chess/skill/node_modules/ava/lib/test-worker.js:89:3)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/greg/projects/alexa-skills/chess/skill/node_modules/ava/lib/test-worker.js:93:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

   1 exception

  ✖ test/index-test.js exited with a non-zero exit code: 1
```

Not sure if the issues are related.  The second issue seems to come after the `ava` build step.

**Comment by ggoforth** [comment]
I'm running:

```
➜  skill node -v
v5.12.0

➜  skill npm -v
3.8.6

➜  skill yo alexa-skill --version
1.8.4
```

**Comment by tjaffri** [comment]
For what it's worth, I don't see this. Here's what I'm running:

``` bash
$ node -v
v6.5.0
$ npm -v
3.10.3
$ yo alexa-skill --version
1.8.5
```
